### ISSUE TITLE
Is there a Windows 64bit software?

### ISSUE THREAD

**Issue by shahabsiavash** [behdad/color-emoji#3]
Hello,

I don't know I should ask this here or not. I know yours is a Python code. But is there any Windows application to create color fonts?

I am actually in the process of designing the first Persian color font. Actually it is finished. I used the FontLab TT and it automatically generates different files based on the current approaches from the major vendors. (Layers, sbix, COLR, SVG)

The problem (?) is that only the SVG works. (of course just in FireFox) others are just b/w and does not work anywhere.

The other weird (to me) thing is I tested the Segoe UI Emoji in FontCreator and it shows all the glyphs in color. But my exported files (even the functional one) still shows up b/w. I mean the Microsoft technique is based on layers and new Unicode tables, but how FontCreator does not load the COLR and CPAL tables and yet show the font in color?

**Comment by behdad** [comment]
No idea why it doesn't work.  Try this one: http://www.fontlab.com/fontlab-pad/

**Comment by behdad** [comment]
No idea why it doesn't work.  Try this one: http://www.fontlab.com/fontlab-pad/
